In [2]:
import pandas as pd

dado_hist = {
    'Empresa 1':[4,9,6,5],
    'Empresa 2':[9,6,4,15],
    'Empresa 3':[6,4,2,25],
    'Empresa 4':[4,2,4,35],
    'Empresa 5':[2,4,9,45]
}

df = pd.DataFrame(dado_hist)

df.loc[0,'Empresa 2'] = -9
df.loc[1,'Empresa 2'] = -6
df.loc[2,'Empresa 2'] = -4
print(df)
df.style.bar(subset=['Empresa 1','Empresa 2'],align='mid',color=['#d65f5f','#5fba7d'])

   Empresa 1  Empresa 2  Empresa 3  Empresa 4  Empresa 5
0          4         -9          6          4          2
1          9         -6          4          2          4
2          6         -4          2          4          9
3          5         15         25         35         45